networks:
  operand-networking:
    driver: bridge

volumes:
  operand-redis-data:

services:
  redis:
    image: redis:7.4
    container_name: operand-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - operand-networking
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      REDIS_HOST: ${REDIS_HOST}
    volumes:
      - operand-redis-data:/data

  operand-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    container_name: operand-app
    networks:
      - operand-networking
    volumes:
      - .:/app
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
